// data/mockData.ts

export const mockTFSWorkItems = [
  ...Array(1).fill([
    {
      id: 1,
      url: "https://tfs.pacific.costcotravel.com/tfs/CostcoTravel/Work%20Items/_workitems/edit/1",
      system: {
        Title: "Sample User Story",
        WorkItemType: "User Story",
        State: "In Progress",
        Reason: "Development",
        AuthorizedAs: "John Doe",
        tags: "frontend;urgent",
        CreatedDate: "2024-12-01T10:00:00.000Z",
        IterationPath: "CostcoTravel\\Sprint01",
      },
      costcoTravel: {
        Team: "Shopping Team 1",
      },
      parsedTags: ["frontend", "urgent"],
      systemDescription: "This is a sample user story for demonstration purposes.",
    },
    {
      id: 2,
      url: "https://tfs.pacific.costcotravel.com/tfs/CostcoTravel/Work%20Items/_workitems/edit/2",
      system: {
        Title: "Login Feature Bug",
        WorkItemType: "Bug",
        State: "New",
        Reason: "Bug Fix",
        AuthorizedAs: "Jane Smith",
        tags: "backend;high-priority",
        CreatedDate: "2024-12-05T14:30:00.000Z",
        IterationPath: "CostcoTravel\\Sprint01",
      },
      costcoTravel: {
        Team: "Authentication Team",
      },
      parsedTags: ["backend", "high-priority"],
      systemDescription: "Users are unable to log in using their credentials.",
    },
    {
      id: 3,
      url: "https://tfs.pacific.costcotravel.com/tfs/CostcoTravel/Work%20Items/_workitems/edit/3",
      system: {
        Title: "Checkout Process Improvement",
        WorkItemType: "Task",
        State: "To Do",
        Reason: "Enhancement",
        AuthorizedAs: "Alice Johnson",
        tags: "frontend;enhancement",
        CreatedDate: "2024-12-10T09:15:00.000Z",
        IterationPath: "CostcoTravel\\Sprint02",
      },
      costcoTravel: {
        Team: "Checkout Team",
      },
      parsedTags: ["frontend", "enhancement"],
      systemDescription: "Improve the checkout flow to reduce cart abandonment.",
    },
    {
      id: 4,
      url: "https://tfs.pacific.costcotravel.com/tfs/CostcoTravel/Work%20Items/_workitems/edit/4",
      system: {
        Title: "Mobile App Performance Issue",
        WorkItemType: "Bug",
        State: "Resolved",
        Reason: "Performance",
        AuthorizedAs: "Bob Lee",
        tags: "mobile;performance",
        CreatedDate: "2024-11-25T16:45:00.000Z",
        IterationPath: "CostcoTravel\\Sprint01",
      },
      costcoTravel: {
        Team: "Mobile Development Team",
      },
      parsedTags: ["mobile", "performance"],
      systemDescription: "App experiences lag during peak usage times.",
    },
    {
      id: 5,
      url: "https://tfs.pacific.costcotravel.com/tfs/CostcoTravel/Work%20Items/_workitems/edit/5",
      system: {
        Title: "Implement Payment Gateway",
        WorkItemType: "Epic",
        State: "In Progress",
        Reason: "New Feature",
        AuthorizedAs: "Carol King",
        tags: "backend;payment",
        CreatedDate: "2024-12-12T11:20:00.000Z",
        IterationPath: "CostcoTravel\\Sprint03",
      },
      costcoTravel: {
        Team: "Payments Team",
      },
      parsedTags: ["backend", "payment"],
      systemDescription: "Integrate a new payment gateway to support additional payment methods.",
    },
    {
      id: 6,
      url: "https://tfs.pacific.costcotravel.com/tfs/CostcoTravel/Work%20Items/_workitems/edit/6",
      system: {
        Title: "User Profile Update",
        WorkItemType: "User Story",
        State: "Done",
        Reason: "Feature Completion",
        AuthorizedAs: "David Kim",
        tags: "frontend;user-profile",
        CreatedDate: "2024-12-08T08:50:00.000Z",
        IterationPath: "CostcoTravel\\Sprint02",
      },
      costcoTravel: {
        Team: "User Experience Team",
      },
      parsedTags: ["frontend", "user-profile"],
      systemDescription: "Allow users to update their profile information and preferences.",
    },
    {
      id: 7,
      url: "https://tfs.pacific.costcotravel.com/tfs/CostcoTravel/Work%20Items/_workitems/edit/7",
      system: {
        Title: "Database Migration",
        WorkItemType: "Task",
        State: "In Progress",
        Reason: "Infrastructure",
        AuthorizedAs: "Evelyn Martinez",
        tags: "backend;database",
        CreatedDate: "2024-12-15T13:10:00.000Z",
        IterationPath: "CostcoTravel\\Sprint04",
      },
      costcoTravel: {
        Team: "Database Team",
      },
      parsedTags: ["backend", "database"],
      systemDescription: "Migrate the existing database to a more scalable solution.",
    },
    {
      id: 8,
      url: "https://tfs.pacific.costcotravel.com/tfs/CostcoTravel/Work%20Items/_workitems/edit/8",
      system: {
        Title: "SEO Optimization",
        WorkItemType: "Task",
        State: "To Do",
        Reason: "Marketing",
        AuthorizedAs: "Frank Nguyen",
        tags: "seo;marketing",
        CreatedDate: "2024-12-18T07:30:00.000Z",
        IterationPath: "CostcoTravel\\Sprint03",
      },
      costcoTravel: {
        Team: "Marketing Team",
      },
      parsedTags: ["seo", "marketing"],
      systemDescription: "Optimize website content and structure for better search engine ranking.",
    },
    {
      id: 9,
      url: "https://tfs.pacific.costcotravel.com/tfs/CostcoTravel/Work%20Items/_workitems/edit/9",
      system: {
        Title: "Accessibility Improvements",
        WorkItemType: "User Story",
        State: "In Progress",
        Reason: "Compliance",
        AuthorizedAs: "Grace Liu",
        tags: "accessibility;frontend",
        CreatedDate: "2024-12-20T12:00:00.000Z",
        IterationPath: "CostcoTravel\\Sprint04",
      },
      costcoTravel: {
        Team: "Accessibility Team",
      },
      parsedTags: ["accessibility", "frontend"],
      systemDescription: "Enhance website accessibility to meet WCAG standards.",
    },
    {
      id: 10,
      url: "https://tfs.pacific.costcotravel.com/tfs/CostcoTravel/Work%20Items/_workitems/edit/10",
      system: {
        Title: "Email Notification System",
        WorkItemType: "Epic",
        State: "New",
        Reason: "Feature Request",
        AuthorizedAs: "Henry Park",
        tags: "backend;notifications",
        CreatedDate: "2024-12-22T15:25:00.000Z",
        IterationPath: "CostcoTravel\\Sprint05",
      },
      costcoTravel: {
        Team: "Notifications Team",
      },
      parsedTags: ["backend", "notifications"],
      systemDescription: "Develop a robust email notification system for various user actions.",
    },
    {
      id: 11,
      url: "https://tfs.pacific.costcotravel.com/tfs/CostcoTravel/Work%20Items/_workitems/edit/10",
      system: {
        Title: "Email Notification System",
        WorkItemType: "Epic",
        State: "New",
        Reason: "Feature Request",
        AuthorizedAs: "Henry Park",
        tags: "backend;notifications",
        CreatedDate: "2024-12-22T15:25:00.000Z",
        IterationPath: "CostcoTravel\\Sprint05",
      },
      costcoTravel: {
        Team: "Notifications Team",
      },
      parsedTags: ["backend", "notifications"],
      systemDescription: "Develop a robust email notification system for various user actions.",
    },
  ]).flat(),
];
